// Code generated by "stringer -trimprefix Kind -type Kind"; DO NOT EDIT.

package xjson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindNull-1]
	_ = x[KindBool-2]
	_ = x[KindNumber-3]
	_ = x[KindString-4]
	_ = x[KindArray-5]
	_ = x[KindObject-6]
}

const _Kind_name = "NullBoolNumberStringArrayObject"

var _Kind_index = [...]uint8{0, 4, 8, 14, 20, 25, 31}

func (i Kind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
